global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-service"
    static_configs:
      - targets: ["api-service:8080"]

  - job_name: "analytics-service"
    static_configs:
      - targets: ["analytics-service:8081"]